### ISSUE TITLE
Compilation error using MySensors 2.1.1

### ISSUE THREAD

**Issue by singinglarvae** [jaysee/teleInfo#2]
Hi there,

I have hot a compilation error using the very last MySensors API (2.1.1). Here goes the log:

`/tmp/ccp3bYa0.ltrans1.ltrans.o: In function 'loop':
/home/marc/Documents/Arduino/Perso/teleInfo/MySensors.ino:238: undefined reference to 'teleInfo::get()'
/tmp/ccp3bYa0.ltrans1.ltrans.o: In function 'setup':
/home/marc/Documents/Arduino/Perso/teleInfo/MySensors.ino:100: undefined reference to 'teleInfo::get()'
/tmp/ccp3bYa0.ltrans2.ltrans.o: In function '__static_initialization_and_destruction_0':
/home/marc/Documents/Arduino/Perso/teleInfo/MySensors.ino:19: undefined reference to 'teleInfo::teleInfo(unsigned char)'
/home/marc/Documents/Arduino/Perso/teleInfo/MySensors.ino:19: undefined reference to 'teleInfo::~teleInfo()'
collect2: error: ld returned 1 exit status
exit status 1
Erreur de compilation pour la carte Arduino Pro or Pro Mini`

I had to make some changes to the code in order to be in compliance with the new API. I am not a GitHub expert, but changes are available here (I guess):
https://github.com/singinglarvae/teleInfo/commit/d3561ae028959702dc16580bf054f4306e374988
Any suggestion would be welcome ;-)

**Comment by jaysee** [comment]
Hi

Thanks for your work, yes my lib was only supporting mySensor API 1.4 using a specific dev tree (see #1).

As i am not using mySensor in any projects for the moment, and I'm not very confortable with new versions, I don't think i will soon have some time to work on it.

For what i cna see, the new version of mySensor seem to have cleanup some things, that a good point! Is your version working using the new mySensor API ?

Thanks .

**Comment by singinglarvae** [comment]
Hi and thanks for your reply,

My version "should" work with the new API 2.1.1. But as mentionned, I have got this very last issue with the "teleInfo" class. Looks like the "get" method is not defined (?).

I am not an arduino expert, but this method is set here, right ? https://github.com/jaysee/teleInfo/blob/master/teleInfo.h#L97

**Comment by jaysee** [comment]
Ok,

I can't see the setup for my lib in your file, there should be : 

```cpp
// teleinfo
#include <SoftwareSerial.h>
#include "teleInfo.h"
#define TI_RX 4
teleInfo TI( TI_RX );
```

at the begining of your file.

**Comment by singinglarvae** [comment]
The code is there. Github just hide this portion of code as it shows only differences between our 2 versions (have a look at line numbers ;-) )

**Comment by jaysee** [comment]
Which version of arduino are you using to build ? I tried using the last one (1.8.2) and it builded fine!

(You need to have the teleInfo.cpp and teleInfo.h files in the same directory as mySensors.ino).

**Comment by singinglarvae** [comment]
:sweat_smile: Oki... forgot to include the teleInfo.cpp file... Compilation went fine. I can not yet test the sensor due to hardware limitation (waiting for new parts), but issue seems to be solved :thumbsup:
